function [] = writeIDonImg(data,overlaySettings,axHand)
%WRITEIDONIMG writes the track index in a box at the centroids of all
%objects at the specified time.
%
%   INPUTS:
%       -data: track data, typically procTracks
%       -overlaySettings: settings specifying pixel size, image size and frame
%       to be displayed. Auto-generated by the overlayTester GUI
%       -axHand: handle to plotting axes
%
%   Author: Oliver J. Meacock, (c) 2020

maxStrLen = ceil(log10(size(data,2)+1));
pxSize = overlaySettings.pixSize;

if isfield(data,'area')
    meanArea = mean(arrayfun(@(x)(nanmean(x.area)),data));
else
    totArea = overlaySettings.maxX*overlaySettings.maxY;
    meanArea = totArea/size(data,2);
end
labelArea = meanArea/2;
labelLen = sqrt(labelArea*maxStrLen);
labelWid = labelArea/labelLen;

sizeOffset = labelLen/(overlaySettings.pixSize*2);
whiteRectX = labelLen/overlaySettings.pixSize;
whiteRectY = labelWid/overlaySettings.pixSize;

ftSize = (500*labelWid)/(overlaySettings.maxY);

for cInd = 1:length(data)
    tInd = find(data(cInd).times == (overlaySettings.showFrame + overlaySettings.frameOffset + 1));
    
    if ~isempty(tInd)
        xPx = round(data(cInd).x(tInd)/pxSize)-sizeOffset;
        yPx = round(data(cInd).y(tInd)/pxSize);
    else %If this frame is in a gap for this track, select the frame nearest to this one to indicate cell position.
%         [~,tInd] = max(data(cInd).times((data(cInd).times < (overlaySettings.showFrame + 1))));
%         
%         if ~isempty(tInd)
%             xPx = round(data(cInd).x(tInd)/pxSize);
%             yPx = round(data(cInd).y(tInd)/pxSize);
%         end
    end
    
    if exist('xPx','var')
        rectangle(axHand,'Position',[xPx+sizeOffset-(whiteRectX/2),yPx-(whiteRectY/2),whiteRectX,whiteRectY],'FaceColor','w');
        text(axHand,xPx,yPx,num2str(cInd),'FontSize',ftSize)
    end
    
    clear xPx
end
