function [] = writeIDonImg(data,overlaySettings,axHand)
%WRITEIDONIMG writes the track index in a box at the centroids of all
%objects at the specified time.
%
%   INPUTS:
%       -data: track data, typically procTracks
%       -overlaySettings: settings specifying pixel size, image size and frame
%       to be displayed. Auto-generated by the overlayTester GUI
%       -axHand: handle to plotting axes

pxSize = overlaySettings.pixSize;
sizeOffset = 0.0045 * (overlaySettings.maxX/overlaySettings.pixSize);
whiteRectX = 0.04 * (overlaySettings.maxX/overlaySettings.pixSize);
whiteRectY = 0.018 * (overlaySettings.maxY/overlaySettings.pixSize);

for cInd = 1:length(data)
    tInd = find(data(cInd).times == (overlaySettings.showFrame + overlaySettings.frameOffset + 1));
    
    if ~isempty(tInd)
        xPx = round(data(cInd).x(tInd)/pxSize)-sizeOffset;
        yPx = round(data(cInd).y(tInd)/pxSize)-sizeOffset;
    else %If this frame is in a gap for this track, select the frame nearest to this one to indicate cell position.
%         [~,tInd] = max(data(cInd).times((data(cInd).times < (overlaySettings.showFrame + 1))));
%         
%         if ~isempty(tInd)
%             xPx = round(data(cInd).x(tInd)/pxSize);
%             yPx = round(data(cInd).y(tInd)/pxSize);
%         end
    end
    
    if exist('xPx','var')
        rectangle(axHand,'Position',[xPx+(sizeOffset*4)-(whiteRectX/2),yPx-(whiteRectY/2),whiteRectX,whiteRectY],'FaceColor','w');
        text(axHand,xPx,yPx,num2str(cInd))
    end
    
    clear xPx
end
