function [TP,FP,TN,FN] = scoreTrackQuality(autoTracks,manualTracks,maxBridge)
%SCORETRACKQUALITY compares the tracks generated by the FAST tracking
%algorithm to a ground truth either generated by from the SPR simulations
%directly, or compiled from manual validation.
% 
%Note that autoTracks and manualTracks are presumed to be in the 'Tracks'
%format structure, as output by doDirectLinkingRedux.
%
%   INPUTS:
%       -autoTracks: The tracks generated by FAST  
%       -manualTracks: The ground truth tracks
%       -maxBridge: The maximal gap-bridging size available to the tracking
%       algorithm. Needed to account for links between timepoints that are
%       further than this value away from one another.
%   
%   OUTPUTS:
%       -TP: The number of true positives (correctly assigned links), on a 
%       per-timepoint basis
%       -FP: The number of false positives (incorrectly assigned links)
%       -TN: The number of true negatives (correctly assigned trajectory
%       end points)
%       -FN: The number of false negatives (prematurely terminated tracks)
%
%   Author: Oliver J. Meacock, 2022

TP = zeros(size(manualTracks,1)-1,1);
FP = zeros(size(manualTracks,1)-1,1);
TN = zeros(size(manualTracks,1)-1,1);
FN = zeros(size(manualTracks,1)-1,1);

for t = 1:size(manualTracks,1)-1
    currAutos = autoTracks{t};
    currManuals = manualTracks{t};
    
    %Some links could not have been generated by the algorithm (if the
    %maximum bridging size was smaller than the actual temporal gap between
    %some links).
    unbridgedLinks = currManuals(:,1) > t + maxBridge;
    currManuals(unbridgedLinks,:) = repmat([NaN,NaN],sum(unbridgedLinks),1);
    
    %If both the target frame and target object are correct, score as True
    %positive:
    TPs = and(currAutos(:,1) == currManuals(:,1),currAutos(:,2) == currManuals(:,2));
    %False positives are all incorrect links (i.e. rows that are not NaNs).
    FPs = and(~isnan(currAutos(:,1)),or(currAutos(:,1) ~= currManuals(:,1),currAutos(:,2) ~= currManuals(:,2)));
    
    %True negatives are where both manual assignment and auto assignment
    %agree on NaN:
    TNs = and(isnan(currAutos(:,1)),isnan(currManuals(:,1)));
    FNs = and(isnan(currAutos(:,1)),~isnan(currManuals(:,1)));
    
    TP(t) = sum(TPs);
    FP(t) = sum(FPs);
    TN(t) = sum(TNs);
    FN(t) = sum(FNs);
end