function [Ms,linSizes] = plotLineageLengthDistribution(procTracks,divisionSettings,axHand)
%PLOTLINEAGELENGTHDISTRIBUTION plots the distribution of lineages in the
%current dataset, as generated by the division detection module.
%Essentially a histogram of the number of tracks contained within each
%lineage. Also indicates the currently selected minimum lineage size with a
%red vertical line.
%
%   INPUTS:
%       -procTracks: Track data, generated by the tracking module and
%       modified by the division detection module. Saved within the
%       Tracks.mat file.
%       -divisionSettings: User-defined settings for running division
%       detection with. Generated by the divisionTracker GUI.
%       -axHand: Handle to the axes into which you want this plot to be
%       inserted
%
%   OUTPUTS:
%       -Ms: The list of foundational tracks (tracks without mothers)
%       -linSizes: The list of the number of descendents of each tracks,
%       indexed in the same way as procTracks (i.e. linSizes(5) indicates
%       the number of descendents of the track stored in procTracks(5)).
%
%   Author: Oliver J. Meacock (c) 2019

linCount = 0;
for i = 1:size(procTracks,2)
    if isempty(procTracks(i).M) %If this is the founder of a lineage
        linCount = linCount + 1;
    end
end

linSizes = zeros(linCount,1);
Ms = zeros(linCount,1);
sInd = 1;
for i = 1:size(procTracks,2)
    if isempty(procTracks(i).M) %If cell has no mother, call it the founder of a new lineage
        linSizes(sInd) = size(getLineageIndices(procTracks,i,0),1);
        Ms(sInd) = i;
        sInd = sInd + 1;
    end
end

cla(axHand)
linCounts = hist(linSizes,1:max(linSizes));
plot(axHand,linCounts,'b')

lims = axis(axHand);
axis(axHand,[0,max(linSizes)+1,lims(3:4)]);
line([divisionSettings.minInc,divisionSettings.minInc],[0,lims(4)],'Color','r','LineWidth',2,'Parent',axHand)

xlabel(axHand,'Lineage size (number of tracks)')
ylabel(axHand,'Number of lineages')